import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import editionsABI from "@zoralabs/nft-drop-contracts/dist/artifacts/ERC721Drop.sol/ERC721Drop.json"
import { Header } from '../components/Header'
import { Footer } from '../components/Footer'
import { useState } from 'react'
import { useContractWrite } from 'wagmi'

const Mint: NextPage = () => {

    const [mintQuantity, setMintQuantity] = useState({
        "1": 1,
        "2": 2,
        "3": 3,
        "4": 4,
        "5": 5,
    })

  // ZORA NFT Edition "purchase" write
    const { data: mintData, isError: mintError, isLoading: cancelAskLoading, isSuccess: cancelAskSuccess, write: cancelAskWrite  } = useContractWrite({
        addressOrName: "0x230864bab819a49a3e3cd634eb266f9042d22e82",
        contractInterface: editionsABI.abi,
        functionName: 'cancelAsk',
        args: [
            mintQuantity
        ],
        onError(error, variables, context) {
            console.log("error", error)
        },
        onSuccess(cancelData, variables, context) {
            console.log("Success!", cancelData)
        },
    })   
    

  return (
    <div className='flex flex-col justify-center h-screen min-h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="flex flex-col items-center">        
        <h1 className="text-white">
          {'<<< ZORA >>>'}
        </h1>
      </main>
    </div>
  )
}

export default Mint
